export const categoriesArray = [
  { value: "Construcion y Remodelación" },
  { value: "Remodelación de departamentos y casas" },
  { value: "Servicios generales por hora" },
  { value: "Plomeria y Calefacción" },
  { value: "Servicios de instalación eléctrica" },
  { value: "Ventanas y balcones" },
  { value: "Servicios de soldadura" },
  { value: "Construcción de casas y cabañas" },
  { value: "Servicio del Sector inmobiliario" },
  { value: "Diseño y presupuesto" },
  { value: "Gestión de propiedades inmobiliarias" },
  { value: "Muebles y decoracion" },
  { value: "Otros servicios de construcción y remodelación" },
  { value: "Fiestas y carnavales" },
  { value: "Bailarines" },
  { value: "Disfraces de carnaval" },
  { value: "Entrenadores personales y coreógrafos" },
  { value: "Fiestas y Eventos" },
  { value: "Catering" },
  { value: "Decoracion" },
  { value: "Presentadores ,músicos y artistas" },
  { value: "Otros servicios de fiestasy carnavales" },
  { value: "Engineering & Architecture" },
  { value: "Belleza" },
  { value: "Manicure y pedicure" },
  { value: "Pestañas y cejas" },
  { value: "Estilista, barbero" },
  { value: "Blower,tinte de pelo y keratina" },
  { value: "Maquillaje" },
  { value: "Tatuaje y piercing" },
  { value: "Otros servicios de belleza" },
  { value: "Servicios profesionales" },
  { value: "Servicios para mascotas" },
  { value: "Paseo de mascotas" },
  { value: "Perreras" },
  { value: "Transporte" },
  { value: "Estética animal" },
  { value: "Otros servicios para mascotas" },
  { value: "Reparacion e instalación de equipos" },
  { value: "Reparacion de pequeños electrodomésticos" },
  { value: "Refrigeradores" },
  { value: "Celulares y tablets" },
  { value: "Reparacion de computadoras" },
  { value: "Televisores" },
  { value: "Aires acondicionados" },
  { value: "Neveras" },
  { value: "Lavadoras" },
  { value: "Otros servicios de equipo" },
  { value: "Servicios domésticos" },
  { value: "Empleada doméstica" },
  { value: "Ayudante" },
  { value: "Limpieza" },
  { value: "Niñeras y enfermeras/os" },
  { value: "Otros servicios domésticos" },
  { value: "Reparacion de automóviles" },
  { value: "Servicio de alquiler de carros" },
  { value: "Servicios de acarreos y Mudanzas" },
  { value: "Servicio especial de pasajeros" },
  { value: "Grúas de remolque" },
  { value: "Asistencia en carretera" },
  { value: "Aire acondicionado y calefacción" },
  { value: "Servicios de neumáticos" },
  { value: "Motor" },
  { value: "Lavado y cuidado de automoviles" },
  { value: "Diagnóstico" },
  { value: "Reparacion de carrocería" },
  { value: "Equipo eléctrico" },
  { value: "Otros servicios de reparación de automóviles" },
  { value: "Maquinaria especial" },
  { value: "Grúas de remolque" },
  { value: "Grúas de carga" },
  { value: "Retiro de escombros" },
  { value: "Camiones de volteos y cargadores" },
  { value: "Aguas residuales y fosas septicas" },
  { value: "Camiones de agua" },
  { value: "Servicios de mudanza y acarreos" },
  { value: "Otros servicios de mudanza" },
  { value: "Organización de eventos" },
  { value: "Organización de eventos corporativos" },
  { value: "Presentadores, músicos y artistas" },
  { value: "Animadores" },
  { value: "Decoración" },
  { value: "Disfraces de carnaval" },
  { value: "Catering" },
  { value: "Publicidad y promoción" },
  { value: "Bailarines" },
  { value: "Otros servicios de organización de eventos" },
  { value: "Yoga" },
  { value: "Servicios Deportivos" },
  { value: "Servicios fitness y entrenamiento" },
  { value: "Servicios de Horeca" },
  { value: "Mesero" },
  { value: "Steward" },
  { value: "Limpieza y lavandería" },
  { value: "Servicio de chefs y auxiliar de cocina" },
  { value: "Servicio de barra" },
  { value: "Servicios de escolta y seguridad privada" },
  { value: "Otros servicios de Horeca" },
  { value: "Servicios de reciclaje" },
  { value: "Computadoras y TI" },
  { value: "Asistencia informática y técnica" },
  { value: "Reparacion de computadoras" },
  { value: "Programación" },
  { value: "Sitio web preconfigurado" },
  { value: "Servicios de niñeras" },
  { value: "Servicios de empleadas domésticas" },
  { value: "Otro servicio de asistencia informática" },
  { value: "Desarrollo web, móvil y de software" },
  { value: "Aplicaciónes moviles" },
  { value: "interfaz" },
  { value: "Programación web" },
  { value: "Desarrollo de videojuegos" },
  { value: "Desarrollo de comercio electrónico" },
  { value: "Aplicaciónes de escritorio" },
  { value: "iOS" },
  { value: "Swift" },
  { value: "Android" },
  { value: "Shopify" },
  { value: "Wordpress" },
  { value: "Chatbots de AI" },
  { value: "Servicios de AI" },
  { value: "Otros servicios de software y AI" },
  { value: "Confección y modistería" },
  { value: "Costura" },
  { value: "Costuras y arreglos" },
  { value: "Disfraces de carnaval" },
  { value: "Clínica de ropa" },
  { value: "Fabricación de joyas" },
  { value: "Otros servicios de confección y modistería" },
  { value: "Blokchain y criptomonedas" },
  { value: "Rubi" },
  { value: "Solidez" },
  { value: "Desarrollo de contratos inteligentes" },
  { value: "Aplicaciones descentralizadas" },
  { value: "Stablecoin" },
  { value: "Criptógrafia" },
  { value: "Trading Bot" },
  { value: "Desarrollo de intercambio" },
  { value: "Wallet" },
  { value: "Crypto wallet" },
  { value: "Blockchain" },
  { value: "hyperledger" },
  { value: "Ethereum" },
  { value: "Bitcoin" },
  { value: "Web3.js" },
  { value: "Crypto" },
  { value: "Web3" },
  { value: "Solana" },
  { value: "Metaverso" },
  { value: "Otros servicios de blockchain y Web 3.0" },
  { value: "Encargados de mantenimiento y logística" },
  { value: "Carge y descargue" },
  { value: "Ayudante" },
  { value: "Supervisor de operaciones" },
  { value: "Picking y Packing" },
  { value: "Operario de producción" },
  { value: "Operario de acondicionamiento y alistamiento" },
  { value: "Operario de montacarga" },
  { value: "Operario de bodega certificado en alturas" },
  { value: "Operario multitarea" },
  { value: "Recogida de basura" },
  { value: "Otros servicios de logística" },
  { value: "Cursos y tutorías" },
  { value: "Idiomas" },
  { value: "Apoyo escolar y universitario" },
  { value: "Informática" },
  { value: "Deportes" },
  { value: "Cursos de cocina" },
  { value: "Cursos de conducción" },
  { value: "Yoga" },
  { value: "Otros servicios de tutorías" },
  { value: "Otros" },
  { value: "Entrega de flores" },
  { value: "Escolta y seguridad privada" },
  { value: "Servicios de seguros" },
  { value: "Servicios de ciberseguridad" },
  { value: "Consultoría de recursos humanos" },
  { value: "Servicios legales y de abogacía" },
  { value: "Viajes y turismo" },
  { value: "Servicios de fotografía y edición" },
  { value: "Servicios de hoteles y resorts" },
  { value: "Servicios de energía solar" },
  { value: "Servicios de jardinería y paisajismo" },
  { value: "Servicios de movilidad eléctrica" },
  { value: "Servicios de Planificaciónes de boda" },
  { value: "Servicios fitness y entrenamiento" },
  { value: "Servicio de Spa y Masajes" },
  { value: "Servicios de coach" },
  { value: "Servicios de medicina y salud" },
  { value: "Servicios de odontogia" },
  { value: "Servicios para senior + 60" },
  { value: "Servicios de belleza estética y cirugía plástica" },
  { value: "Servicios turísticos" },
  { value: "Guía turístico" },
  { value: "Transporte turístico" },
  { value: "Otros servicios turísticos" },
  { value: "Servicios de hospedaje" },
  { value: "Alquileres vacacional" },
  { value: "Cabañas" },
  { value: "Fincas vacacionales" },
  { value: "Hostal" },
  { value: "Hotel campestre" },
  { value: "Hotel con piscina" },
  { value: "Hotel familiar" },
  { value: "Zonas de camping" },
  { value: "Otros servicios de hospedaje" },
  { value: "Alquiler de inmuebles" },
  { value: "Alquiler de departamentos" },
  { value: "Alquiler de casas" },
  { value: "Lotes y terrenos" },
  { value: "Otros servicios de inmuebles" },
  { value: "Servicios de domicilios" },
  { value: "Domicilios" },
  { value: "Recoger y entregar paquetes" },
  { value: "Trámites y diligencias" },
  { value: "Servicio de taxi" },
  { value: "Conductor en ciudad moto" },
  { value: "Conductor en ciudad carro" },
  { value: "Repartidor" },
  { value: "Conductor de una ciudad a otra" },
  { value: "Conductor de flete" },
  { value: "Otros servicios de transporte y entregas" },
  { value: "Otros" },
  { value: "Servicio de comida a domicilio y restaurantes" },
  { value: "Comida preparada y por encargo" },
  { value: "Catering" },
  { value: "Chefs" },
  { value: "Comida saludable" },
  { value: "Comida vegetariana" },
  { value: "Desayunos" },
  { value: "Almuerzos" },
  { value: "Pizza" },
  { value: "Hamburguesas" },
  { value: "Pollo" },
  { value: "Comida colombiana" },
  { value: "Comida rápida" },
  { value: "Arepas" },
  { value: "Carne" },
  { value: "Comida internacional" },
  { value: "Postres" },
  { value: "Mariscos" },
  { value: "Helados" },
  { value: "Tortas" },
  { value: "Sushi" },
  { value: "Snacks" },
  { value: "Sándwiches" },
  { value: "Salchichas" },
  { value: "Comida árabe" },
  { value: "Comida típica" },
  { value: "Parrilla" },
  { value: "Jugos y batidos" },
  { value: "Empanadas" },
  { value: "Panadería" },
  { value: "Café" },
  { value: "Perros calientes" },
  { value: "Pescados y mariscos" },
  { value: "Poke" },
  { value: "Alitas" },
  { value: "Comida china" },
  { value: "Comida india" },
  { value: "Crepes" },
  { value: "Comida italiana" },
  { value: "Comida mexicana" },
  { value: "Comida asiática" },
  { value: "Comida peruana" },
  { value: "Comida latina" },
  { value: "Servicio de parqueadero" },
  { value: "Alquiler de espacio privado para reparto de comida" },
  { value: "Alquiler de espacio de trabajo y oficina" },
  { value: "Alquiler de cocina comercial" },
  { value: "Alquiler de cocinas compartidas" },
  { value: "Alquiler de helicópteros" },
  { value: "Alquiler de lanchas y barcos" },
  { value: "Alquiler de champlin" },
  { value: "Alquiler de bicicletas eléctricas" },
  { value: "Alquiler de bicicletas" },
  { value: "Alquiler de scooters" },
  { value: "Servicio por encargo" },
  { value: "Alquiler de automoviles de alta gama y de lujo" },
  { value: "Alquiler de novia" },
  { value: "Alquiler de novio o amigos" },
  { value: "Gimnasio" },
  { value: "Servicio de alquiler de herramientas de construcción" },
  {
    value: "Alquiler de Andamios",
  },
  {
    value: "Alquiler de Escaleras",
  },
  {
    value: "Alquiler de Herramientas Eléctricas (taladros, sierras, etc.)",
  },
  {
    value: "Alquiler de Excavadoras",
  },
  {
    value: "Alquiler de Grúas",
  },
  {
    value: "Alquiler de Volquetas",
  },
  {
    value: "Alquiler de Herramientas para Trabajos en Altura",
  },
  {
    value: "Alquiler de Herramientas para Trabajos en Espacios Confinados",
  },
  {
    value:
      "Otros servicios de alquiler de herramientas y equipos de construcción",
  },
  { value: "Masajes para mujeres" },
  { value: "Estudio de uñas para mujeres" },
  { value: "Salon de peluquería para mujeres" },
  { value: "Salon de peluquería para hombres" },
  { value: "Estudio de maquillaje y estilismo" },
  { value: "Salon de peluquería de lujo" },
  { value: "Spa de lujo" },
  { value: "Masaje para hombres" },
  { value: "Extensiones de pestañas y uñas" },
  { value: "Salon de belleza de lujo para mujeres" },
  { value: "Salon de belleza para mujeres" },
  { value: "Servicios de corte, salón y barbería para hombres" },
  { value: "Masajes para hombres" },
  { value: "Masajes para mujeres" },
  { value: "Masajes para parejas" },
  { value: "Salon de lujo para hombres" },
  { value: "Limpieza profunda de cocina y baño" },
  { value: "Limpieza profunda de sofás y alfombras" },
  { value: "Servicio de limpieza y Reparacion de aire acondicionado" },
  { value: "Limpieza por horas" },
  { value: "manicure y pedicure" },
  { value: "Servicio de limpieza interna" },
  { value: "Servicio integral de pintura casa completa" },
  { value: "Servicio de decoración de paredes y paneles de pared" },
  { value: "Servicios pintura parcial de habitaciones/ paredes" },
  { value: "Reparacion de ósmosis inversas o purificadores de agua" },
  { value: "Instalación de ventiladores" },
  { value: "Montaje de muebles de IKEA" },
  { value: "Reparacion de microondas" },
  { value: "Reparacion de chimeneas y vitrocerámicas" },
  { value: "Reparacion de computadora portátil" },
  { value: "Enfriador de aire" },
  { value: "Montaje de muebles" },
  { value: "Cocina" },
  { value: "Electricista" },
  { value: "Estudio de maquillaje y estilismo" },
  { value: "Servicio de depilación láser" },
  { value: "Servicio de control de plagas" },
  { value: "Control de chinches" },
  { value: "Control de termitas" },
  { value: "Servicios de desinfección" },
  { value: "Servicios de control de cucarachas , hormigas y chinches" },
  { value: "Servicios de control de moscas , mosquitos y roedores" },
  { value: "Servicio de lavandería y tintorería" },
  { value: "Cuidador/a a domicilio" },
  { value: "Cocineros" },
  { value: "Limpieza de tanques de agua" },
  { value: "Servicio alquiler de vehículos de lujo" },
  { value: "Servicio  de alquiler carro" },
  { value: "Servicio de alquiler moto" },
  { value: "Servicio alquiler de lanchas y barcos" },
  { value: "Servicios de diseño y creatividad" },
  { value: "Diseño de logotipos" },
  { value: "Diseño web y móvil" },
  { value: "Diseño de materiales de marketing" },
  { value: "Diseño de identidad de marca" },
  { value: "Diseño de embalaje y etiquetas" },
  { value: "Diseño de interfaces de usuario (UX)" },
  { value: "Arte e ilustración" },
  { value: "Diseño de gráficos para streamers y redes sociales" },
  { value: "Diseño de anuncios de banner" },
  { value: "Diseño de productos" },
  { value: "Otros servicios de diseño y creatividad" },
];
