export const categoriesArray = [
  { value: "Servicios de belleza & Higiene" },
  { value: "Servicio de estética" },
  { value: "servicio de Cosmetología" },
  { value: "servicio de Peluquería & barberia" },
  { value: "Servicio de contabilidad" },
  { value: "Servicio de Contabilidad financiera" },
  { value: "Servicio de asesoría financiera" },
  { value: "Servicio de asesoría fiscal" },
  { value: "Servicio del Sector inmobiliario" },
  { value: "Fotografía comercial" },
  { value: "Gestión de propiedades inmobiliarias" },
  { value: "Gestión de contenido empresarial " },
  { value: "Servicios de Seguros" },
  { value: "Servicios de ciberseguridad" },
  { value: "Consultoría de recursos humano" },
  { value: "Cursos y Clases" },
  { value: "WebMobile & Software dev" },
  { value: "Fiestas y Eventos" },
  { value: "Hogar y Oficina" },
  { value: "IT & Networking" },
  { value: "Mantenimiento de vehículos" },
  { value: "Medicina y Salud" },
  { value: "Engineering & Architecture" },
  { value: "Desing & Creative" },
  { value: "Writing" },
  { value: "Translation" },
  { value: "Investigación de mercado" },
  { value: "Legal" },
  { value: "Admin Support" },
  { value: "Customer Service" },
  { value: "Sales & Marketing" },
  { value: "Servicios profesionales" },
  { value: "Servicios de reparaciones e Instalaciones" },
  { value: "servicios de Ropa e indumentaria" },
  { value: "Servicios para mascotas" },
  { value: "Servicios de transporte" },
  { value: "Viajes y turismo" },
  { value: "Accounting and Consulting Specialist" },
  { value: "Gaming" },
  { value: "Blockchain & Crypto" },
  { value: "Audio Video Production" },
  { value: "Servicio de modistería" },
  { value: "Offline" },
  { value: "NFT" },
  { value: "Influencers" },
  { value: "Article Writer" },
  { value: "Servicios de diseño gráfico" },
  { value: " Servicios de diseño web y de aplicaciones" },
  { value: "Servicios de dibujo e ilustración" },
  { value: "Servicios de diseño de marketing" },
  { value: "Servicios de fotografía  y edición" },
  { value: "Servicios de audio y música" },
  { value: "AI services" },
  { value: "Servicios de alquiler de carros" },
  { value: "Servicios de hoteles y Resorts" },
  { value: "paquetes turísticos" },
  { value: "Servicios de acarreos y Mudanzas" },
  { value: "Servicio especial de pasajeros" },
  { value: "Servicios de alquiler y otros" },
  { value: "Servicios de mensajería y delivery" },
  { value: "Servicios de limpieza" },
  { value: "Servicios de desinfeccion" },
  { value: " Servicios de logística" },
  { value: " Servicios de energía Solar" },
  { value: "Servicios de jardineria y paisajismo”" },
  { value: " Servicios de minería" },
  { value: "Servicios de construcción" },
  { value: "Servicios de manicure y Pedicure" },
  { value: "Servicios de gastronomía y cocina" },
  { value: "Servicios de movilidad eléctrica" },
  { value: "Consultoría medioambiental" },
  { value: "Normativa de Startups" },
  { value: "Servicios de mezcla de música(DJ)" },
  { value: "Servicios de planificaciónes de bodas" },
  { value: "Servicios de préstamos hipotecarios" },
  { value: "Ferias comerciales" },
  { value: "Bienes inmuebles comerciales" },
  { value: "Eventos corporativos" },
  { value: "Formación de directivos" },
  { value: "Reparación de equipos informáticos" },
  { value: "Planificación financiera" },
  { value: "Diseño de logotipos" },
  { value: "Servicios de piercings y tatuajes" },
  { value: "Cursos de conducción" },
  { value: "Cursos de cocina" },
  { value: "Idiomas" },
  { value: "Musica" },
  { value: "Yoga" },
  { value: " Servicios Deportivos" },
  { value: "Servicios fitness y entrenamiento" },
  { value: "SEO" },
  { value: "Servicios de lavado de vehículos" },
  { value: "SEM" },
  { value: "Spa y Masajes" },
  { value: "Servicio de Catering" },
  { value: "Servicio de barra" },
  { value: "Servicios de escolta y seguridad privada" },
  { value: "Servicio de aseo" },
  { value: "Servicios de reciclaje" },
  { value: "Servicios de coach" },
  { value: "Servicios de electricista" },
  { value: "Servicios de salud mental" },
  { value: "Servicios de medicina y salud" },
  { value: "Servicios para seniors + 60" },
  { value: "Servicios de niñeras" },
  { value: "Servicios de empleadas domésticas" },
  { value: "Otros" },
];
