export const skillsArray = [
  { value: "Análisis" },
  { value: "Análisis modal de fallos y efectos" },
  { value: "Análisis de peligros y puntos de control críticos" },
  { value: "Análisis web" },
  { value: "Asistencia ejecutiva" },
  { value: "AWS" },
  { value: "Asistencia sanitaria" },
  { value: "Servicio de atención al cliente" },
  { value: "Organizaciones sin ánimo de lucro" },
  { value: "Cuentas a pagar" },
  { value: "Cuentas a cobrar" },
  { value: "A++" },
  { value: "Aptitudes para hacer presentaciones" },
  { value: "Adobe Photoshop" },
  { value: "Adobe Illustrator" },
  { value: "Adobe InDesign" },
  { value: "Adobe Creative Suite" },
  { value: "Angular" },
  { value: "Aseguramiento de la calidad" },
  { value: "Administración de oficina " },
  { value: "Adaptabilidad" },
  { value: "Análisis de datos" },
  { value: "Capacidad de análisis" },
  { value: "Analítica" },
  { value: "Análisis de requisitos" },
  { value: "API" },
  { value: "AutoCAD" },
  { value: "Android" },
  { value: "API REST" },
  { value: "Java" },
  { value: "JavaScript" },
  { value: "Administración de clientes" },
  { value: "Administración de las tecnologías de la información" },
  { value: "Administración logística" },
  { value: "Acción comunitaria" },
  { value: "Administración de proyectos" },
  { value: "Administración de oficinas" },
  { value: "Asistencia virtual" },
  { value: "Analítica de datos" },
  { value: "Análisis de datos" },
  { value: "Administración de alimentos y medicamentos" },
  { value: "Administración de empresas" },
  { value: "Análisis financiero" },
  { value: "Análisis crítico" },
  { value: "Administración de redes" },
  { value: "ASP.NET" },
  { value: "Adaptabilidad" },
  { value: "Angular" },
  { value: "Administración de la cadena de suministros" },
  { value: "Administración de ventas" },
  { value: "Administración de contratos" },
  { value: "Google Ads" },
  { value: "Administración de información" },
  { value: "Aptitudes de organización" },
  { value: "Asistencia telefónica" },
  { value: "Asesoramiento" },
  { value: "Aplicaciones web" },
  { value: "Azure" },
  { value: "Análisis de control de calidad" },
  { value: "Administración de riesgos" },
  { value: "Análisis de negocio " },
  { value: "Apache ZooKeeper" },
  { value: "Metodologías agiles " },
  { value: "Azure" },
  { value: "Base de datos" },
  { value: "Banca de inversión" },
  { value: "Branding" },
  { value: "Alimentación y bebidas" },
  { value: "Bootstrap" },
  { value: "Bootstrapping" },
  { value: "Bussiness Development" },
  { value: "Marketing" },
  { value: "PostgreSQL " },
  { value: "MongoDb" },
  { value: "JavaScript" },
  { value: "SEO" },
  { value: "Soporte vital básico " },
  { value: "SQL" },
  { value: "SQL Server" },
  { value: "MySQL" },
  { value: "Biotecnología" },
  { value: "Biología" },
  { value: "Bienestar" },
  { value: "Investigación" },
  { value: "Biología molecular" },
  { value: "Boletines informativos" },
  { value: "Liderazgo" },
  { value: "Beneficios para empleados" },
  { value: "Planificación estratégica" },
  { value: "Estrategia de marketing" },
  { value: "Banca minorista" },
  { value: "Bioestadística" },
  { value: "Bases de datos" },
  { value: "C++" },
  { value: "Programación en C" },
  { value: "C#" },
  { value: "CMS" },
  { value: "CSCA" },
  { value: "Citrix XenApp" },
  { value: "Cooking" },
  { value: "Consultorías" },
  { value: "Gestión de cuentas" },
  { value: "Gestión de cambio estructural" },
  { value: "CAD" },
  { value: "Ciencia de datos" },
  { value: "Capacidad de análisis" },
  { value: "Calidadsaludseguridad y Medioambiente" },
  { value: "Capacidad de adaptación" },
  { value: "Comunicación" },
  { value: "Comunicaciones unificadas" },
  { value: "Comunicación efectiva" },
  { value: "Comunicaciones" },
  { value: "Coaching" },
  { value: "Comercialización" },
  { value: "Comercialización visual" },
  { value: "Comercio minorista" },
  { value: "Contratación de personal" },
  { value: "Satisfacción del cliente" },
  { value: "CSS" },
  { value: "CRM" },
  { value: "Crecimiento de las ventas" },
  { value: "Creación de contenido" },
  { value: "Contabilidad" },
  { value: "Consultoría" },
  { value: "Creatividad" },
  { value: "Creativo" },
  { value: "Cocinar" },
  { value: "Confiabilidad" },
  { value: "Colaboración" },
  { value: "CSS3" },
  { value: "Coordinación" },
  { value: "Control de calidad" },
  { value: "Computación en la nube" },
  { value: "Ciencias de la computación" },
  { value: "Ciencias de la salud" },
  { value: "Negociación de contratos" },
  { value: "Consultoría de recursos humanos" },
  { value: "Construcción" },
  { value: "Cuidado de la salud" },
  { value: "Ciencias naturales" },
  { value: "Coordinación de proyectos" },
  { value: "Mejora continua" },
  { value: "Consultoría de estrategia" },
  { value: "Calidad" },
  { value: "Compasión" },
  { value: "Community Management" },
  { value: "Control de crédito" },
  { value: "Comunicaciones de marketing" },
  { value: "Conocimientos informáticos" },
  { value: "Desarrollo empresarial" },
  { value: "Liderazgo de equipos" },
  { value: "Gestión de proyectos" },
  { value: "Integración de equipos" },
  { value: "Gestión de ventas" },
  { value: "Gestión del tiempo" },
  { value: "Gestión de programas" },
  { value: "Planificación de proyectos" },
  { value: "Data bases" },
  { value: "Docencia" },
  { value: "Docencia universitaria" },
  { value: "Desarrollo de oportunidades de negocio" },
  { value: "Diseño" },
  { value: "Diseño de la interfaz de usuario" },
  { value: "Diseño de experiencia de usuario (UX)" },
  { value: "Diseño digital" },
  { value: "Destreza" },
  { value: "Diseño urbano" },
  { value: "Dreamweaver" },
  { value: "Dart" },
  { value: "Desarrollo de software" },
  { value: "Desarrollo de productos" },
  { value: "Desarrollo de talento" },
  { value: "Desarrollo web" },
  { value: "Desarrollo movil" },
  { value: "Docker" },
  { value: "Django" },
  { value: "Backend development" },
  { value: "Frontend development" },
  { value: "Desarrollo de liderazgo" },
  { value: "Desarrollo profesional" },
  { value: "Desarrollo empresarial" },
  { value: "Desarrollo de software" },
  { value: "Deportes" },
  { value: "Diseñar" },
  { value: "Diseño de software" },
  { value: "Diseño asistido por ordenador (CAD)" },
  { value: "Diseño gráfico" },
  { value: "Diseño UI" },
  { value: "Diseño UX" },
  { value: "Diseño web" },
  { value: "Diseño visual" },
  { value: "Disciplina" },
  { value: "Diseño de logotipos" },
  { value: "Documentación" },
  { value: "Desarrollo de iOS" },
  { value: "Desarrollo de Android" },
  { value: "Digitador" },
  { value: "Dirección y desarrollo de equipos de trabajo" },
  { value: "Elaboración de presupuestos" },
  { value: "Marketing de redes" },
  { value: "Desarrollo de negocios " },
  { value: "DO#" },
  { value: "Enseñanza superior" },
  { value: "Educación" },
  { value: "E-commerce" },
  { value: "Educación a distancia" },
  { value: "Estrategia de ventas" },
  { value: "Estrategia de precios" },
  { value: "Estrategia digital" },
  { value: "Editar" },
  { value: "Edición de video" },
  { value: "Emprendimiento" },
  { value: "Entretenimiento" },
  { value: "Experiencia de usuario" },
  { value: "Experiencia de usuario" },
  { value: "Estadística" },
  { value: "Microsoft Excel" },
  { value: "Excel avanzado" },
  { value: "Expreso.js" },
  { value: "Electrónica" },
  { value: "Educación primaria y secundaria" },
  { value: "Educación Tech" },
  { value: "Entrenamiento de desarrollo" },
  { value: "Educación de la salud" },
  { value: "Entrada de datos" },
  { value: "Entrenamiento" },
  { value: "Eventos" },
  { value: "Hablar en público" },
  { value: "Estrategia empresarial" },
  { value: "Estratégico" },
  { value: "Estrategia de TI" },
  { value: "Estrategia de mercadeo" },
  { value: "Estrategia de ventas" },
  { value: "Estrategia de negocios" },
  { value: "Evaluación del talento" },
  { value: "Trabajo en equipo" },
  { value: "Eficiencia" },
  { value: "Empatía" },
  { value: "Experiencia del cliente" },
  { value: "Experiencia de usuario" },
  { value: "Integración de equipos" },
  { value: "Edición" },
  { value: "Escritura" },
  { value: "Entrepreneurship" },
  { value: "E-Learning" },
  { value: "Elaboración de presupuesto" },
  { value: "Estrategia" },
  { value: "Enseñanza" },
  { value: "Espíritu empresarial" },
  { value: "Español" },
  { value: "Escucha activa" },
  { value: "Extraertransformar y cargar (ETL)" },
  { value: "F#" },
  { value: "Fiber to the x (FTTx)" },
  { value: "Formación" },
  { value: "Finanzas" },
  { value: "Fotografía" },
  { value: "Elaboración de informes financieros" },
  { value: "Captación de fondos" },
  { value: "Contabilidad financiera" },
  { value: "Firebase" },
  { value: "Facturación" },
  { value: "Flutter" },
  { value: "Fármacos" },
  { value: "Fintech" },
  { value: "Microsoft Office" },
  { value: "Facebook" },
  { value: "Facilidad de palabra" },
  { value: "Fabricación" },
  { value: "Fusiones y adquisiones" },
  { value: "Física" },
  { value: "Flexibilidad" },
  { value: "Flujo de trabajo" },
  { value: "Flash" },
  { value: "Fisioterapia" },
  { value: "Fluidez verbal" },
  { value: "Factor de aplicaciones" },
  { value: "Fotografía documental" },
  { value: "Filosofía" },
  { value: "Finanzas comerciales" },
  { value: ".NET Framework" },
  { value: "Estrategia de fijación de precios" },
  { value: "Financiación" },
  { value: "Filantropía" },
  { value: "Frontend" },
  { value: "Finanzas públicas" },
  { value: "Fotografía de producto" },
  { value: "Formación y desarrollo" },
  { value: "Formación de empleados" },
  { value: "Finanzas corporativas" },
  { value: "Frances" },
  { value: "Elaboración de modelos financieros" },
  { value: "Fuerzas armadas" },
  { value: "Gestión" },
  { value: "Gestión del tiempo" },
  { value: "Gestión y dirección hotelera" },
  { value: "Google AdWords" },
  { value: "Google Analytics" },
  { value: "Gestión de relación con el cliente" },
  { value: "Gestión de relaciones" },
  { value: "Gestión de recursos humanos" },
  { value: "Gestión operativa" },
  { value: "Gestión administrativa" },
  { value: "Gestión de personas" },
  { value: "Gestión  de inventarios" },
  { value: "Gestión de calidad" },
  { value: "Gestión del tiempo " },
  { value: "Gestión de equipos" },
  { value: "Gestión de clientes" },
  { value: "Gestión de riesgos" },
  { value: "Gestión de contratos" },
  { value: "Gestión de la comunidad" },
  { value: "Gestión de productos" },
  { value: "Consultoría de gestión" },
  { value: "Gestión de proveedores" },
  { value: "Gestión de proyectos" },
  { value: "Gestión de inmuebles y servicios" },
  { value: "Gerencia" },
  { value: "Gestión de oficina" },
  { value: "Gestión comunitaria" },
  { value: "Gestión de relaciones con el cliente" },
  { value: "Gestión contable" },
  { value: "Gestión de la innovación" },
  { value: "Gestión del rendimiento " },
  { value: "Gestión de programas" },
  { value: "Gestión logística" },
  { value: "Gestión del talento" },
  { value: "Gestión de voluntariado" },
  { value: "Gestión del cambio" },
  { value: "Gestión de obras de construcción" },
  { value: "Gestión sanitaria" },
  { value: "Gestión de servicios de Ti" },
  { value: "Gestión de pérdidas y ganancias" },
  { value: "Gestión de operaciones" },
  { value: "GIT" },
  { value: "GITHUB" },
  { value: "Google Analytics" },
  { value: "HTML" },
  { value: "HTML5" },
  { value: "HSEQ" },
  { value: "Hacking" },
  { value: "Hackear" },
  { value: "Habilidades sociales" },
  { value: "Herramientas de desarrollador" },
  { value: "Herramientas Nocode" },
  { value: "Herramientas de diseño" },
  { value: "Herramientas educativas" },
  { value: "Hablar en público" },
  { value: "Gerencia de hoteles" },
  { value: "Habilidades de entrevista" },
  { value: "Hotelería" },
  { value: "Gestión y dirección hotelera" },
  { value: "Historia clínica electrónica (HCE)" },
  { value: "Hospitalidad" },
  { value: "Holandés" },
  { value: "Préstamos hipotecarios" },
  { value: "Integración" },
  { value: "Investigación y desarrollo(I+D)" },
  { value: "Investigación" },
  { value: "Ingles" },
  { value: "Investigación académica" },
  { value: "Ingeniería" },
  { value: "Imaginación" },
  { value: "Ingenieríaaprovisionamiento y construcción" },
  { value: "Internet Strategy" },
  { value: "Ingeniería de software" },
  { value: "Ingeniería industrial" },
  { value: "Ingeniería de ventas" },
  { value: "Ingeniería mecatrónica" },
  { value: "Ingeniería mecánica" },
  { value: "Industria del petróleo y del gas" },
  { value: "Inteligencia emocional" },
  { value: "Ingeniería de datos" },
  { value: "Investigación del usuario" },
  { value: "Investigación cualitativa" },
  { value: "Ilustrador" },
  { value: "Ilustración" },
  { value: "Impresoras" },
  { value: "Investigación de mercados" },
  { value: "Inteligencia empresarial" },
  { value: "Inteligencia de negocio" },
  { value: "Investigación de UX" },
  { value: "Introducción de datos" },
  { value: "Innovación" },
  { value: "Investigación web" },
  { value: "Investigación de mercado" },
  { value: "Investigación del comportamiento" },
  { value: "Publicidad en internet" },
  { value: "Sector inmobiliario" },
  { value: "Inspección" },
  { value: "Investigación clínica" },
  { value: "Ingeniería de proyectos" },
  { value: "IT" },
  { value: "Inteligencia artificial" },
  { value: "Investigación académica" },
  { value: "Informes financieros" },
  { value: "Information Architeture" },
  { value: "User interface" },
  { value: "Asistencia jurídica gratuita" },
  { value: "Node.js" },
  { value: "Plataforma java" },
  { value: "JSON" },
  { value: "React.js" },
  { value: "Java" },
  { value: "Jira" },
  { value: "JavaScript" },
  { value: "Java Server Pages" },
  { value: "Java8" },
  { value: "Planificación de la jubilación" },
  { value: "Procesos judiciales" },
  { value: "Sistema judicial penal" },
  { value: "Jefe de operaciones" },
  { value: "Apache Kafka" },
  { value: "Kotlin" },
  { value: "Implementación KPI" },
  { value: "Paneles KPI" },
  { value: "KeyShot" },
  { value: "Kronos" },
  { value: "Keras" },
  { value: "KnocKout.js" },
  { value: "Kit de desarrollo de software" },
  { value: "Kali Linux" },
  { value: "Control de tiempo de kronos" },
  { value: "KINIME" },
  { value: "Laravel" },
  { value: "Lenguaje unificado de modelado (UML)" },
  { value: "Legal" },
  { value: "Laborioso" },
  { value: "Logística de producción" },
  { value: "Literatura" },
  { value: "Lean manufacturing" },
  { value: "Leardeship" },
  { value: "Logística" },
  { value: "Linux" },
  { value: "Lingüística" },
  { value: "Liderar" },
  { value: "Localización" },
  { value: "Lightroom" },
  { value: "Leardership" },
  { value: "Lenguajes de programación" },
  { value: "Relaciones con los empleados" },
  { value: "Participación de los trabajadores en la empresa" },
  { value: "Aseguramiento de la calidad" },
  { value: "Computación en la nube" },
  { value: "Aptitudes para la supervisión" },
  { value: "Tecnologías de la información" },
  { value: "Litigación" },
  { value: "Optimización del rendimiento" },
  { value: "Liderazgo" },
  { value: "Látex" },
  { value: "Laravel" },
  { value: "Listas de correo WordPress" },
  { value: "Liderazgo estratégico" },
  { value: "Liderazgo de equipos multifuncional" },
  { value: "Liderazgo organizacional" },
  { value: "Relaciones con los medios de comunicación" },
  { value: "Liderazgo escolar" },
  { value: "Liderazgo de equipos" },
  { value: "Limpieza de oficina" },
  { value: "Liderazgo de equipos" },
  { value: "Locución" },
  { value: "Logística general" },
  { value: "Logística" },
  { value: "Mantenimiento y reparaciones" },
  { value: "Mac OS X Server" },
  { value: "Microsoft Outlook" },
  { value: "Mando(unidad militar)" },
  { value: "Manufactura" },
  { value: "Medios de comunicación" },
  { value: "Mejora de procesos de negocio" },
  { value: "Mejora continua" },
  { value: "MongoDB" },
  { value: "Management" },
  { value: "Machine learning" },
  { value: "Mercado digital" },
  { value: "Mecanografía" },
  { value: "Mercados capitales" },
  { value: "Microsoft SQL Server" },
  { value: "Mercadeo" },
  { value: "Mercadología" },
  { value: "MySQL" },
  { value: "Manejo de ventas" },
  { value: "Manejo de clientes" },
  { value: "Manejo administrativo" },
  { value: "MATLAB" },
  { value: "Microsoft Office" },
  { value: "Mercadeo digital" },
  { value: "Metodologías agiles" },
  { value: "Mesa de ayuda" },
  { value: "Manejo de riesgos" },
  { value: "Marketing" },
  { value: "Marketing interno" },
  { value: "Manejo logístico" },
  { value: "Marketing educativo" },
  { value: "Mercadeo de producto" },
  { value: "Marketing de contenidos" },
  { value: "Manejo de efectivo" },
  { value: "Manejo de tiempo" },
  { value: "Manejo de relaciones" },
  { value: "Manejo de redes sociales" },
  { value: "Marketing de redes sociales" },
  { value: "Matemáticas" },
  { value: "Micro servicios" },
  { value: "Microsoft Word" },
  { value: "Microsoft SQL Server" },
  { value: "Mobile development" },
  { value: "Negociaciones" },
  { value: "Procesos de negocio" },
  { value: "Petróleo y gas natural" },
  { value: "Narración de historias" },
  { value: "Narración" },
  { value: "Node.js" },
  { value: "Nest.js" },
  { value: ".NET" },
  { value: "ASP.NET" },
  { value: "NIIF" },
  { value: "NetBeans" },
  { value: "Neo4j" },
  { value: "New media" },
  { value: "npm" },
  { value: "Negocios internacionales" },
  { value: "Networking empresarial" },
  { value: "Negociación" },
  { value: "Nanotecnología" },
  { value: "Negociación de venta" },
  { value: "Normas de calidad" },
  { value: "Negociación de contrato" },
  { value: "Negocios económicos" },
  { value: "Nomina de sueldos" },
  { value: "Nomina de pagos" },
  { value: "Nomina de SAP" },
  { value: "Redes sociales" },
  { value: "Noción" },
  { value: "Nuevos medios de comunicación" },
  { value: "Normas ISO" },
  { value: "Nutrición" },
  { value: "Negotiation" },
  { value: "Neurociencia" },
  { value: "Organización" },
  { value: "Office 365" },
  { value: "Oficina de gestión de proyectos" },
  { value: "Oficina virtual" },
  { value: "Oracle database" },
  { value: "Oracle" },
  { value: "Ofimática" },
  { value: "Organización de eventos" },
  { value: "Organización de viajes" },
  { value: "Organización logística" },
  { value: "Organización de equipos de trabajo" },
  { value: "Operaciones" },
  { value: "Oratoria" },
  { value: "Online Marketing" },
  { value: "Operaciones de cuentas" },
  { value: "Operaciones contables" },
  { value: "Operaciones de marketing" },
  { value: "Operaciones TI" },
  { value: "Operaciones de mercadeo" },
  { value: "Operaciones de venta" },
  { value: "Operaciones de negocios" },
  { value: "Operaciones bancarias" },
  { value: "Operaciones de recursos humanos" },
  { value: "Operaciones comerciales" },
  { value: "Sistemas operativos" },
  { value: "Orientado al detalle" },
  { value: "Optimización" },
  { value: "Optimización de procesos" },
  { value: "Onboarding" },
  { value: "Optimización de funnel" },
  { value: "Odontología" },
  { value: "Oncología" },
  { value: "Pruebas de aceptación del usuario" },
  { value: "Pensamiento estratégico" },
  { value: "Pensamiento analítico" },
  { value: "Priorización" },
  { value: "Planificación" },
  { value: "PowerPoint" },
  { value: "Power Pivot" },
  { value: "Proactivo" },
  { value: "Productividad" },
  { value: "Relaciones públicas" },
  { value: "Psicología" },
  { value: "Proyectos" },
  { value: "Product desing" },
  { value: "PostgreSQL" },
  { value: "Planificación" },
  { value: "Planificación de negocios" },
  { value: "Procesos de negocios" },
  { value: "Project Management" },
  { value: "Planificación estratégica" },
  { value: "Publicidad" },
  { value: "Publicidad digital" },
  { value: "Programación en C" },
  { value: "Programación" },
  { value: "Pronostico" },
  { value: "Pensamiento crítico" },
  { value: "Resolución de problemas" },
  { value: "Photoshop" },
  { value: "Planeación" },
  { value: "Planeación estratégica" },
  { value: "Planeamiento estratégico" },
  { value: "Planeación de eventos" },
  { value: "Productos SAP" },
  { value: "Producción" },
  { value: "Presupuesto" },
  { value: "Periodismo" },
  { value: "Pedagogía" },
  { value: "Pago de nóminas" },
  { value: "Psicoterapia" },
  { value: "Python" },
  { value: "PHP" },
  { value: "QuarkXPress" },
  { value: "HP QTP" },
  { value: "Química de proteínas" },
  { value: "Quirófano" },
  { value: "QlikView" },
  { value: "Calidad de servicio(QoS)" },
  { value: "Gestión de quejas" },
  { value: "Qt" },
  { value: "QA" },
  { value: "Quirúrgico" },
  { value: "Quantum GIS" },
  { value: "Química de los polímeros" },
  { value: "Química" },
  { value: "Rayos X" },
  { value: "REST" },
  { value: "RESTful" },
  { value: "Difracción de rayos X de polvo" },
  { value: "Reclutamiento" },
  { value: "Resolución de conflictos" },
  { value: "Realización de pruebas" },
  { value: "Recaudación de fondos" },
  { value: "Resolución de problemas" },
  { value: "Relaciones con los empleados" },
  { value: "Relaciones laborales" },
  { value: "Relaciones interpersonales" },
  { value: "Relaciones con clientes" },
  { value: "Relaciones públicas" },
  { value: "Relaciones internacionales" },
  { value: "Planificación de recursos empresariales" },
  { value: "Redacción" },
  { value: "Redacción publicitaria" },
  { value: "Redacción de textos" },
  { value: "Redacción de contenido" },
  { value: "Redacción de contenido web" },
  { value: "Redacción medica" },
  { value: "Redacción de investigaciones" },
  { value: "Relaciones con los medios de comunicación" },
  { value: "Relaciones comunitarias" },
  { value: "Redes" },
  { value: "Redes sociales" },
  { value: "Resiliencia" },
  { value: "Resolución imaginativa de problemas" },
  { value: "Responsabilidad social" },
  { value: "Clases de repaso" },
  { value: "Recursos humanos" },
  { value: "Reanimación cardiopulmonar" },
  { value: "Inmuebles residenciales" },
  { value: "Recopilación de datos" },
  { value: "Renderizado 3d" },
  { value: "Redes de computadoras" },
  { value: "React" },
  { value: "React native" },
  { value: "React.js" },
  { value: "Ruby" },
  { value: "Ruby on Rails" },
  { value: "Revit" },
  { value: "Startups" },
  { value: "SQL" },
  { value: "Servidor SQL" },
  { value: "Software development" },
  { value: "Servicio de atención al cliente" },
  { value: "Salud" },
  { value: "Servicio al cliente" },
  { value: "Seguridad" },
  { value: "Satisfacción del cliente" },
  { value: "Seis sigma" },
  { value: "Social media" },
  { value: "Social networking" },
  { value: "Servicios financieros" },
  { value: "Ciclo de vida de desarrollo de software (SDLC)" },
  { value: "Sanidad" },
  { value: "Salud pública" },
  { value: "Sector de exploración y producción" },
  { value: "Seguros" },
  { value: "Seguros de bienes y responsabilidad civil" },
  { value: "Seguro de calidad" },
  { value: "Sostenibilidad" },
  { value: "Supervisión" },
  { value: "Soporte" },
  { value: "Soporte vital básico" },
  { value: "Soporte técnico" },
  { value: "Soporte remoto" },
  { value: "Soporte administrativo" },
  { value: "Soporte de ventas" },
  { value: "Soporte de operaciones" },
  { value: "Soporte ejecutivo" },
  { value: "Sector inmobiliario" },
  { value: "Scrum" },
  { value: "Selenium" },
  { value: "Sass" },
  { value: "Saas" },
  { value: "Spring Framework" },
  { value: "Symfony" },
  { value: "Servicios web" },
  { value: "Solución de problemas" },
  { value: "SWIFT" },
  { value: "SPARK" },
  { value: "SoapUI" },
  { value: "Tableau" },
  { value: "TypeScript" },
  { value: "Trabajo cooperativo" },
  { value: "Terapia" },
  { value: "Terapia de familia" },
  { value: "Tecnología de la información" },
  { value: "Transporte" },
  { value: "Televisión" },
  { value: "Traducción" },
  { value: "Traducción al español" },
  { value: "Transcripción" },
  { value: "Transcripción de audio" },
  { value: "Turismo" },
  { value: "Tutorías" },
  { value: "Tutoría en línea" },
  { value: "Testing manual" },
  { value: "Tesorería" },
  { value: "Tipografía" },
  { value: "Tercerización de servicios" },
  { value: "Tecnología" },
  { value: "Tecnología inalámbrica" },
  { value: "Telecomunicaciones" },
  { value: "Tecnologías de información en sanidad" },
  { value: "Transformación digital" },
  { value: "Trabajo en equipo" },
  { value: "Trabajar en equipo" },
  { value: "Trabajo en grupo" },
  { value: "Talento humano" },
  { value: "Trabajo remoto" },
  { value: "Toma de decisiones" },
  { value: "Telemercadeo" },
  { value: "Televentas" },
  { value: "Tributación" },
  { value: "Tecnologías blockchain" },
  { value: "Unix" },
  { value: "Unity" },
  { value: "Usability" },
  { value: "User interface" },
  { value: "Viviendas unifamiliares" },
  { value: "Ventas" },
  { value: "Ventas y servicio al cliente" },
  { value: "Ventas B2B" },
  { value: "Venta de soluciones" },
  { value: "Ventas de tecnología" },
  { value: "Ventas por catálogo" },
  { value: "Ventas de comida" },
  { value: "Ventas telefónicas" },
  { value: "Ventas farmacéuticas" },
  { value: "Ventas directas" },
  { value: "Ventas previa" },
  { value: "Ventas de software" },
  { value: "Ventas consultivas" },
  { value: "Video" },
  { value: "Video marketing" },
  { value: "Videografía" },
  { value: "Verificación de datos" },
  { value: "Validación de datos" },
  { value: "Ventas minoristas" },
  { value: "Virtualización" },
  { value: "Microsoft Visio" },
  { value: "Visualización de datos" },
  { value: "Ventas internacionales" },
  { value: "VMware" },
  { value: "Voz sobre IP(VoIP)" },
  { value: "Visual Studio Code" },
  { value: "Vue.js" },
  { value: "Vuetify" },
  { value: "Windows" },
  { value: "Windows 7" },
  { value: "Windows XP" },
  { value: "Web master" },
  { value: "Web Marketing" },
  { value: "Web desing" },
  { value: "Web 2.0" },
  { value: "Web 3.0" },
  { value: "Web Proyect Management" },
  { value: "Web application development" },
  { value: "Web development" },
  { value: "WordPress" },
  { value: "X++" },
  { value: "XML" },
  { value: "XAMPP" },
  { value: "OS X" },
  { value: "XHTML" },
  { value: "XSLT" },
  { value: "Xcode" },
  { value: "Xamarin" },
  { value: "Xbox 360" },
  { value: "YouTube" },
  { value: "Yii" },
  { value: "Yii 2.O" },
  { value: "Yoga" },
  { value: "Zoho" },
  { value: "Zoom" },
  { value: "Zapier" },
  { value: "Zbrush" },
  { value: "Zend" },
  { value: "Zephyr" },
  { value: "Zumba" },
  { value: "Zona única de pagos en euros" },
  { value: "Zimbra" },
  { value: "ZipBee" },
  { value: "ZFS" },
  { value: "Zabbix" },
  { value: "Zemax" },
  { value: "Zona de recepción" },
];
