import preferenceModel from "../models/preference";
export const createPreferences = async () => {
  try {
    const countPreferences = await preferenceModel.estimatedDocumentCount();
    if (countPreferences > 0) return;
    await preferenceModel.insertMany([
      { value: "QA & Review" },
      { value: "Estilo & Imagen" },
      { value: "V eo & Audio" },
      { value: "Writing & Translation" },
      { value: "Game Art" },
      { value: "Fotografía" },
      { value: "Artesanías" },
      { value: "Festiv ades & Ferias" },
      { value: "Street" },
      { value: "AR & VR" },
      { value: "Diseño de personajes" },
      { value: "Diseño de automoción & Vehículos" },
      { value: "Ropa" },
      { value: "Diseño industrial" },
      { value: "Diseño de moda" },
      { value: "Diseño interactivo" },
      { value: "Direccion artística" },
      { value: "Gráficos animados" },
      { value: "Dirección" },
      { value: "Dirección creativa" },
      { value: "Diseño de aplicaciones" },
      { value: "Música" },
      { value: "Visualización" },
      { value: "Visualización de arquitectura" },
      { value: "Twitch Store " },
      { value: "Interfax & Exp. de usuario" },
      { value: "Técnicas de proyección audiovisual" },
      { value: "Diseño de superficies" },
      { value: "Joyería" },
      { value: "Movimiento en 3d" },
      { value: "Gastronomía" },
      { value: "Lifestyle" },
      { value: "Jewelry Desing" },
      { value: "Nanotecnología" },
      { value: "Robótica" },
      { value: "Graficos para streamers" },
      { value: "Arqueología" },
      { value: "Moda" },
      { value: "Building Engineering" },
      { value: "Landscape Desing" },
      { value: "Arquitecture & interior desing" },
      { value: "Photoshop" },
      { value: "Children’s Book Illustration " },
      { value: "Learning analytics" },
      { value: "Ingeniería cuántica" },
      { value: "Fashion Desing" },
      { value: "Fact Checking " },
      { value: "Bussines plans" },
      { value: "Financial consulting " },
      { value: "Legal consulting " },
      { value: "Portraits & Caricatures " },
      { value: " Presentation Desing" },
      { value: "Edición" },
      { value: "Content Creators" },
      { value: "Develop a brand  entify" },
      { value: "Real Estate" },
      { value: "Industrial & Product Desing" },
      { value: "Backgroung Removal" },
      { value: "Infographic Desing" },
      { value: "Cine" },
      { value: "Viajes & Turismo" },
      { value: "Transporte & Viajes" },
      { value: "Articles & Blog Posts " },
      { value: "Blockchain & Cryptocurrency" },
      { value: " Diseño de tarjetas & material de oficina" },
      { value: "Astronautas" },
      { value: "Arquitectura e ingeniería 3d" },
      { value: "Desarrollo de dispositivos wearables" },
      { value: "Diseño de logotipos" },
      { value: "Fintech" },
      { value: "Piloto de drones" },
      { value: "Servicios de mercadeo" },
      { value: "Soporte técnico" },
      { value: "Artistas de AI" },
      { value: "Desarrollo de chatbots" },
      { value: "Nanotecnología & Biotech" },
      { value: "Genetista" },
      { value: "Animacion de logos" },
      { value: "Tarjeta de presentación & Papelería" },
      { value: "Arquitectura" },
      { value: "Diseño de redes sociales" },
      { value: "Metaverso" },
      { value: "Diseño de objetos o accesorios" },
      { value: "Maquillaje & Cu ado de la piel" },
      { value: "Tatuajes & piercings" },
      { value: "Fitness & Deportes" },
      { value: "Servicios de personalización e imagen de marca" },
      { value: "Diseño de embalajes" },
      { value: "Diseño de libros" },
      { value: "Diseño de portadas de álbumes" },
      { value: "Diseño de señaletica" },
      { value: "Nocode developers" },
      { value: "Desarrollo de software" },
      { value: "Gestion de Proyectos" },
      { value: "Medicina & Salud" },
      { value: "Diseño de invitaciones" },
      { value: "Camisetas & Productos promocionales" },
      { value: "Diseño de carteles" },
      { value: "Diseño de sitios web" },
      { value: "Diseño de folletos & Panfletos" },
      { value: "Diseño de experiencias de usuario (UX)" },
      { value: "Diseño de páginas de destino" },
      { value: "Desarrollo web & Aplicaciones" },
      { value: "Diseño de aplicaciones" },
      { value: "Diseño de iconos" },
      { value: "Ilustraciones" },
      { value: "Retratos" },
      { value: "Dibujos animados & Comics" },
      { value: "Diseño de moda" },
      { value: "Marketig de influencia" },
      { value: "Guiones gráficos" },
      { value: "Biología" },
      { value: "Historia" },
      { value: "Ingeniería aeroespacial & Exploración espacial" },
      { value: "Diseño de tatuajes" },
      { value: "Design" },
      { value: "Arte NFT & Web3.0" },
      { value: "Development & IT" },
      { value: "Diseño para medios sociales" },
      { value: "Diseño de correos electrónicos" },
      { value: "Anuncios tipo banner" },
      { value: "Diseño de presentaciones" },
      { value: "Diseño de infografías" },
      { value: "Diseño de currículos" },
      { value: "Marketing de influencia" },
      { value: "Data Science" },
      { value: "Redaccion" },
      { value: "Fotografia de productos" },
      { value: "Trafico web" },
      { value: "Energías renovables & Medio ambiente" },
      { value: "Fotografia local" },
      { value: "Edición & Retoque de imágenes" },
      { value: "Marketing para medios sociales" },
      { value: "Voice over" },
      { value: "Fotografia de retratos" },
      { value: " Diseño gráfico" },
      { value: "Analyze bussiness data" },
      { value: "UX & UI" },
      { value: "Admin & Customer  Support" },
      { value: "Consulting & HR" },
      { value: "Ventas" },
      { value: "Business consulting " },
      { value: "Event Management " },
      { value: "Marketing" },
      { value: "Manage data" },
      { value: "Diseño de moda" },
      { value: "Get creative with arts and crafts" },
      { value: "Ecommerce" },
      { value: "Focus on personal growth" },
      { value: "Asesoría & Mentoria" },
      { value: "Terapia & Salud mental" },
      { value: "Contabil ad & Finanzas" },
      { value: "Banca & Servicios financieros" },
      { value: "Servicio al cliente" },
      { value: "Análisis de datos" },
      { value: "Produce a podcast" },
      { value: "Book & e-book Publishing" },
      { value: "Arquitectura & Diseño de interiores" },
      { value: "Mascotas" },
      { value: "Arte digital" },
      { value: "Virtual Assistant" },
      { value: "E-Commerce Management " },
      { value: "Dibujos en CAD" },
      { value: "Market Research " },
      { value: "Sales" },
      { value: "Cine" },
      { value: "Artes culinarias" },
      { value: "Arquitectura de información" },
      { value: "Arte urbano" },
      { value: "Animación GIF" },
      { value: "Artes escénicas" },
      { value: "Diseño paisajistico" },
      { value: "Diseño de mobiliario" },
      { value: "Landing Page Desing" },
      { value: "Efectos visuales" },
      { value: "Modelado 3d" },
      { value: "Web Banners" },
      { value: "Vector Tracing" },
      { value: "Servicios de arquitectura" },
      { value: "Estilismo gastronómico" },
      { value: "Modelos arquitectónicos" },
      { value: "Cosmetics Formulation" },
      { value: "Pattern Design" },
      { value: "Resume Desing" },
      { value: "Escenografía" },
      { value: "Escritura de guiones visuales" },
      { value: "Diseño de calzado" },
      { value: "Efectos visuales" },
      { value: "Redacción & Traducción" },
      { value: "Soporte administrativo" },
      { value: "Storyboards" },
      { value: "Hogar inteligente" },
      { value: "Animales & veterinaria" },
      { value: "Agronomía" },
      { value: " Nutrition" },
      { value: "Diseño de vestuario" },
      { value: "Customer Care" },
      { value: "Diseño de juguetes" },
      { value: "Juguetes y juegos" },
      { value: "Flyer Desing" },
      { value: "Brochure Desing" },
      { value: "Poster Desing" },
      { value: "Catalog Desing" },
      { value: "Menu Desing" },
      { value: "Entretenimiento & Recreacion" },
      { value: "Edición" },
      { value: "Diseño de exposiciones" },
      { value: "Educatión " },
      { value: "Experiencia de usuario" },
      { value: "CRM management " },
      { value: "Investigación" },
      { value: "Fotografía" },
      { value: "Gastronomía" },
      { value: "ERP management " },
      {
        value: "Tecnología de la información & Comunicaciones (TIC)",
      },
      { value: "Character Modelling" },
      { value: "Legal & judicial Consulting " },
      { value: "Supply Chain Management " },
      { value: " Project management " },
      { value: "AI services" },
      { value: "Data  Model Training " },
      { value: "Voice Synthesis & AI" },
      { value: "Fact Checking" },
      { value: "AI Content Editing" },
      { value: "Todo en AI services" },
      { value: "Build yor AI app" },
      { value: "Data Science AI" },
      { value: "Insumos & Maquinarias" },
      { value: "Data labeling & Annotation" },
      { value: "AI Artists" },
      { value: "AI Music V eos" },
      { value: "Data Analytics" },
      { value: "Photo Manipulation" },
      { value: "Game Art" },
      { value: "Graphics for streamers" },
      { value: "Desing Advice" },
      { value: "Social Media Marketing" },
      { value: "Search Engine Optimizacion(SEO)" },
      { value: "Local SEO" },
      { value: "Marketig Strategy" },
      { value: "Public Relations" },
      { value: "Guest Posting" },
      { value: "Marketing Advice" },
      { value: "V eo Marketing" },
      { value: "Email Marketing" },
      { value: "Web Analytics" },
      { value: "Text Message Marketing" },
      { value: "Crowdfunding" },
      { value: "Search Engine Marketing(SEM)" },
      { value: "Dispaly Advert ing" },
      { value: "Influencer  Marketing" },
      { value: "Community Management" },
      { value: "Mobilie App Marketing" },
      { value: "Music Promotion" },
      { value: "Book & eBook Marketing" },
      { value: "Podcast Marketing" },
      { value: "Photography" },
      { value: "Product Photographers" },
      { value: "Lifestyle & Fashion Phptographers" },
      { value: "Real Estate Photographers" },
      { value: "Event Photographers" },
      { value: "Food Photographers" },
      { value: "Aerial Photographers" },
      { value: "Photography Advice" },
      { value: "Portrait Photographers" },
      { value: "Logo & Brand  entity" },
      { value: "Gaming" },
      { value: "Lifestyle" },
      { value: "Online Tutoring" },
      { value: "Career Counseling" },
      { value: "Game Coaching" },
      { value: "Life Coaching" },
      { value: "Fitness" },
      { value: "Nutrition" },
      { value: "Wellness" },
      { value: "Modelling & Acting" },
      { value: "Styling & Beauty" },
      { value: "Trend Forecasting" },
      { value: "Astrology & Psychics" },
      { value: "Arts & Crafts" },
      { value: "Gaming" },
      { value: "Puzzle & Game Creation" },
      { value: "Traveling" },
      { value: "Collectibles" },
      { value: "Family & Genealogy" },
      { value: "Website Development" },
      { value: "Website Mintenance" },
      { value: "WordPress" },
      { value: "Shopify" },
      { value: "Bussiness Websites" },
      { value: "E-Commerce Development" },
      { value: "Landing Pages" },
      { value: "Blogs" },
      { value: "Game Development" },
      { value: "Development For Streamers" },
      { value: "Software Development" },
      { value: "Movile Apps" },
      { value: "Web Applications" },
      { value: "Desktop Applications" },
      { value: "AI Coding & Development" },
      { value: "DevOps & Cloud" },
      { value: "Support & IT" },
      { value: "Cybersecurity" },
      { value: "Electronic Engineering" },
      { value: "Chatbots Development" },
      { value: "Online Coding Lessons" },
      { value: "Convert  Files" },
      { value: "User Testing" },
      { value: "Music & Audio" },
      { value: "Producers & Composers" },
      { value: "Mixing & Mastering" },
      { value: "Singers & Vocalists" },
      { value: "Session Musicians" },
      { value: "Songwriters" },
      { value: "Beat Making" },
      { value: "Jingles & Intros" },
      { value: "Online Music Lessons" },
      { value: "Music Transcription" },
      { value: "Remixing & Mashups" },
      { value: "Meditation Music" },
      { value: "Synth Presets" },
      { value: "Voice Over" },
      { value: "Podcast Production" },
      { value: "Audiobook Production" },
      { value: "Sound Desing" },
      { value: "Audio Ads Production" },
      { value: "DJ Drops & Tags" },
      { value: "DJ  Mixing" },
      { value: "Audio Logo & Sonic Branding" },
      { value: "Voice Synthesis & AI" },
      { value: "Music & Audio Advice" },
      { value: "Vocal Tuning" },
      { value: "V eo  & Animation" },
      { value: "V eo Editing" },
      { value: "V eo Ads & Commercials" },
      { value: "Animated Explainers" },
      { value: "Character Animation" },
      { value: "Music V eo" },
      { value: "Logo Animation" },
      { value: "Lottie & Web Animation" },
      { value: "Intro & Outro V eos" },
      { value: "Rigging" },
      { value: "Visual Effects" },
      { value: "Social Media V eos" },
      { value: "V eographers" },
      { value: "V eo Advice" },
      { value: "Subtitles & Captions" },
      { value: "App & Website Previews" },
      { value: "3D Product  Animation" },
      { value: "E-commerce Product V eos" },
      { value: "Spokesperson V eos" },
      { value: "Animated GIFs" },
      { value: "Unboxing V eos" },
      { value: "Corporate V eos" },
      { value: "Sl eshow V eos" },
      { value: "Meditation V eos" },
      { value: "Live Action Explainers" },
      { value: "Game Trailers" },
      { value: "Book Trailers" },
      { value: "NFT Animation" },
      { value: "Animation for Streamers" },
      { value: "Animation for K s" },
      { value: "Article to V eo" },
      { value: "Real Estate Promos" },
      { value: "eLearning V eo Production" },
      { value: "V eo Templates Editing" },
      { value: "Screencasting V eos" },
      { value: "Articles & Blog Post" },
      { value: "Writing & Translation" },
      { value: "Localization" },
      { value: "Contend Strategy" },
      { value: "Translation" },
      { value: "Proofreading & Editig" },
      { value: "Resume Writing" },
      { value: "Cover Letters" },
      { value: "Linkelind Profiles" },
      { value: "Ad Copy" },
      { value: "Sales Copy" },
      { value: "Social Media Copy" },
      { value: "Email Copy" },
      { value: "Case Studies" },
      { value: "Book & eBook Writing" },
      { value: "Book Editing" },
      { value: "Scriptwriting" },
      { value: "Podcast Writing" },
      { value: "Beta Reading" },
      { value: "Creative Writing" },
      { value: "Brand Voice & Tone" },
      { value: "Ux Writing" },
      { value: "Speechwriting" },
      { value: "eLearning Content Development" },
      { value: "Technical Writing" },
      { value: "Job Descriptions" },
      { value: "White Papers" },
      { value: "Website Content" },
      { value: "Product Descriptions" },
      { value: "Press Releases" },
      { value: "Bussines Names & Slogans" },
      { value: "Grant Writing" },
      { value: "Transcription" },
      { value: "Research & Summaries" },
      { value: "Writing Advice" },
      { value: "Databases" },
      { value: "Data Processing" },
      { value: "Data Analytics" },
      { value: "Data Visualization" },
      { value: "Data Engineering" },
      { value: "Data Science & AI" },
      { value: "Data  Entry" },
      { value: "Data Governance & Protection" },
      { value: "Data Formatting & Cleaning" },
      { value: "Data Labeling & Annotation" },
      { value: "Data Mining & Scraping" },
      { value: "Data  Entry" },
      { value: "Graphics for Streamers" },
      { value: "Game Concept Desing" },
      { value: "Event Management" },
      { value: "Data Visualization" },
      { value: "Presentations" },
      { value: "Data Analytics" },
      { value: "Fonts & Typography" },
      { value: "Bussines cards & Stationery" },
      { value: "Brand Style Gu es" },
      { value: "Database" },
      { value: "Data visaualization" },
      { value: "Hoteles & Alojamientos" },
      { value: "Comercial e industrial" },
      { value: "Restaurante" },
      { value: "Servicios profesionales" },
      { value: " Noticias & Medios de comunicacion" },
      { value: "Bienes raices" },
      { value: "Influenciador en redes sociales" },
      { value: "Cosmetica,belleza y cu ado personal" },
      { value: "Call center bilingue" },
      { value: "Comercial en call center" },
      { value: "Servicio al cliente en Call center" },
      { value: "Auxiliares de tienda" },
      { value: "Cajeros" },
      { value: "Impulsadores" },
      { value: "Operario" },
      { value: "Vendedores TaT" },
      { value: "Economía estatal & Empresarial" },
      { value: "Influencer  Marketing" },
      { value: " Todo en consultoría RRHH & RhTech" },
      { value: "Mercados financieros de largo plazo" },
      { value: "Industria química & Farmacéutica " },
      { value: "Manufactura" },
      { value: "Comercio internacional" },
      { value: "Fisioterapia" },
      { value: "Grafiti" },
      { value: "Astronomia & Astrofisica" },
      { value: "Cientifico de datos" },
      { value: "Cannabis" },
      { value: "Retiros & Spa" },
      { value: "Creative Challenges" },
      { value: "Fotogramas con estilo" },
      { value: "Creacion de paquetes de musica" },
      { value: "Illustrator" },
      { value: "Lightroom" },
      { value: "InDesing" },
      { value: "XD" },
      { value: "Figma" },
      { value: "Herramientas creativas" },
      { value: "Comic" },
      { value: "Redaccion de currículums" },
      { value: "Todo en consultoria de Cirugia plastica" },
      { value: "todo en consultoria de Odontologia" },
      { value: "Otros" },
    ]);
    console.log("susses create preferences in database");
  } catch (error) {
    console.log(error);
  }
};
